name: Build artifact on PR

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  build:
    name: Build Release artifacts
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git show -s --format=%h)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app_${{steps.vars.outputs.sha_short}}_${{github.run_number}}.apk
          path: build/app/outputs/flutter-apk/app-release.apk