name: Dart CI

on: 
  push:
    branches:    
      - master 

jobs:
  jobLinux:
    name: Build Release artifacts
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --debug --no-codesign
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.ipa,build/app/outputs/apk/debug/*.apk"
        tag: ${{github.run_number}}
        token: ${{ secrets.TOKEN }}